import { useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { recipes } from "@/data/mockRecipes";
import { colors, SuggestionChip } from "@/components/ui";
import { RecipeCard } from "@/components/RecipeCard";
import { EmptyState, ErrorState, LoadingRecipeCards, OfflineBanner } from "@/components/states";
export default function RecipeResults(){const router=useRouter();const {state: initialState}=useLocalSearchParams<{state?:string}>();const [query,setQuery]=useState("High-protein dinner under 30 minutes");const [filter,setFilter]=useState("Best match");const [state,setState]=useState(initialState==="error"?"error":initialState==="empty"?"empty":"loading");useEffect(()=>{if(state!=="loading")return;const timer=setTimeout(()=>setState("results"),900);return()=>clearTimeout(timer)},[state]);const retry=()=>setState("loading");return <ScrollView style={styles.page} contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><Text>‹</Text></Pressable><Text style={styles.title}>Meal ideas</Text><View style={{width:44}}/></View><TextInput value={query} onChangeText={setQuery} style={styles.query}/><OfflineBanner onRetry={retry}/>{state==="loading"?<LoadingRecipeCards/>:state==="error"?<ErrorState onRetry={retry} onBack={()=>router.replace("/(tabs)")}/>:state==="empty"?<EmptyState title="No good matches found" text="Try changing your request or adding a few more ingredients." actionLabel="Add ingredients" onAction={()=>router.push("/(tabs)/pantry")}/>:<><Text style={styles.heading}>Best matches</Text><Text style={styles.support}>Using Chicken, Eggs, Tomato, Onion and Rice</Text><View style={styles.filters}>{["Best match","Fastest","High protein"].map(f=><SuggestionChip key={f} label={f} selected={filter===f} onPress={()=>setFilter(f)}/>)}</View><View style={styles.cards}>{recipes.map(r=><RecipeCard key={r.id} recipe={r} onPress={()=>router.push(`/recipes/${r.id}`)}/>)}</View><Pressable onPress={()=>setState("empty")}><Text style={styles.test}>Show no-results state</Text></Pressable><Pressable onPress={()=>setState("error")}><Text style={styles.test}>Show error state</Text></Pressable></>}</ScrollView>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:"white"},content:{padding:20,paddingTop:54,paddingBottom:32,gap:14},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{width:44,height:44,justifyContent:"center",alignItems:"center",borderWidth:1,borderColor:colors.border,borderRadius:22},title:{fontSize:20,fontWeight:"700"},query:{minHeight:64,borderWidth:1,borderColor:colors.border,borderRadius:10,padding:12,fontSize:16},heading:{fontSize:22,fontWeight:"700",marginTop:6},support:{fontSize:14,color:colors.textSecondary},filters:{flexDirection:"row",flexWrap:"wrap",gap:8},cards:{gap:12},test:{fontSize:13,color:colors.textSecondary,textAlign:"center",padding:5}});
