import { ingredients } from "../data/ingredients";
import { ingredientCategories } from "../data/ingredient-categories";
import { matchRecipeToPantry } from "../domain/ingredients/ingredient-matcher";
import { resolveIngredient } from "../domain/ingredients/ingredient-normalizer";
import { searchIngredients } from "../domain/ingredients/ingredient-search";
import { validateIngredientDataset } from "../domain/ingredients/ingredient-validator";
import { PantryItem, RecipeIngredient } from "../domain/ingredients/ingredient.types";
const expect=(condition:unknown,message:string)=>{if(!condition)throw new Error(message)};
const resolve=(term:string)=>resolveIngredient(term,ingredients)?.id;
expect(resolve("capsicum")==="bell-pepper","capsicum resolves to Bell Pepper");
expect(resolve("aubergine")==="eggplant","aubergine resolves to Eggplant");
expect(resolve("brinjal")==="eggplant","brinjal resolves to Eggplant");
expect(resolve("coriander leaves")==="cilantro","coriander leaves resolves to Cilantro");
expect(resolve("garbanzo beans")==="chickpeas","garbanzo beans resolves to Chickpeas");
expect(searchIngredients("caps",ingredients)[0]?.ingredient.id==="bell-pepper","alias prefix search ranks Bell Pepper");
expect(searchIngredients("beans",ingredients).some(({ingredient})=>ingredient.id==="cannellini-beans"),"word search finds Cannellini Beans");
const pantry=(...ids:string[]):PantryItem[]=>ids.map((ingredientId,index)=>({id:`p${index}`,userId:"u",ingredientId,createdAt:"2026-01-01",updatedAt:"2026-01-01"}));
const recipe=(...rows:[string,boolean?][]):RecipeIngredient[]=>rows.map(([ingredientId,isOptional],index)=>({id:`r${index}`,recipeId:"r",ingredientId,isOptional:!!isOptional}));
expect(matchRecipeToPantry(pantry("red-onion"),recipe(["onion"]),ingredients).matchPercentage===100,"red onion satisfies onion");
expect(matchRecipeToPantry(pantry("onion"),recipe(["onion"]),ingredients).matchPercentage===100,"preparation stays outside identity");
expect(matchRecipeToPantry(pantry("greek-yogurt"),recipe(["sour-cream"]),ingredients).matchPercentage===0,"no implicit substitution");
const match=matchRecipeToPantry(pantry("tomato","rice","onion"),recipe(["tomato"],["onion"],["garlic"],["rice"],["cilantro",true]),ingredients);
expect(match.matchPercentage===75&&match.missingIngredients[0]?.ingredientId==="garlic","required match is 75 percent and optional does not penalize");
expect(validateIngredientDataset(ingredients,ingredientCategories).length===0,"seed dataset validates");
