import { baseDietSelection, normalizePreferenceStorage } from "../domain/preferences/preference-serialization";
import { mergePreferenceMutation, rollbackPreferenceMutation } from "../domain/preferences/preference-mutation";
import type { BaseDiet } from "../domain/preferences/dietary";
const expect = (condition: unknown, message: string) => { if (!condition) throw new Error(message); };
const base = { dietPreferences: ["Vegan"], baseDiet: "vegan" as BaseDiet, glutenFree: true, dairyFree: true, allergies: ["Milk"], nutritionGoals: ["High protein"], avoidedIngredients: [{ type: "canonical" as const, ingredientId: "milk" }], units: "Metric" as const, notificationsEnabled: true, appearance: "System default" };
const serialized = normalizePreferenceStorage(base);
expect(serialized.base_diet === "vegan" && serialized.gluten_free && serialized.dairy_free, "independent restrictions serialize together");
expect(serialized.cooking_preferences.avoidedIngredients[0]?.type === "canonical", "canonical exclusions are preserved");
expect(normalizePreferenceStorage({ ...base, baseDiet: null, dietPreferences: ["Eggetarian"] }).base_diet === "eggetarian", "legacy base diet maps safely");
expect(normalizePreferenceStorage({ ...base, baseDiet: null, dietPreferences: ["Jain"] }).diet[0] === "Jain", "unmapped legacy diet JSON is preserved");
expect(baseDietSelection(["Vegan"], "Pescatarian").join() === "Pescatarian", "base diets are mutually exclusive");
expect(baseDietSelection(["Vegan"], null).length === 0, "base diet can be cleared");
expect(rollbackPreferenceMutation(base) === base, "failed preference mutations restore the prior cached preference object");
const glutenOnly = mergePreferenceMutation(base, { glutenFree: false });
expect(glutenOnly.dairyFree && glutenOnly.allergies[0] === "Milk", "saving gluten-free preserves dairy-free and allergies");
const dairyOnly = mergePreferenceMutation(base, { dairyFree: false });
expect(dairyOnly.glutenFree && dairyOnly.avoidedIngredients[0]?.ingredientId === "milk", "saving dairy-free preserves gluten-free and canonical exclusions");
const switchedDiet = mergePreferenceMutation(base, { baseDiet: "vegetarian", dietPreferences: ["Vegetarian"] });
expect(switchedDiet.glutenFree && switchedDiet.dairyFree, "changing base diet preserves independent restrictions");
