import { useState } from "react";
import { Alert, Pressable, ScrollView, Text, View } from "react-native";
import { useRouter } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Info } from "lucide-react-native";
import { PrimaryButton, SecondaryButton, colors } from "@/components/ui";
import { radius, spacing, typography } from "@/theme";
import { useSupabaseSession } from "@/context/SupabaseSessionContext";
import { useUserPreferences } from "@/hooks/usePreferences";
import { useProfile } from "@/hooks/useProfile";
import { useDeviceOnboardingCompletion } from "@/lib/onboarding-completion";
import type { UserPreferences } from "@/context/AppContext";

const defaultPreferences: UserPreferences = { dietPreferences: ["No preference"], nutritionGoals: [], allergies: [], avoidedIngredients: [], units: "Metric", notificationsEnabled: true, appearance: "System default" };
const diets = ["No preference", "Vegetarian", "Non-vegetarian", "Vegan", "Eggetarian"];
const goals = ["High protein", "Balanced", "Low calorie", "High fiber"];
const allergies = ["Peanuts", "Milk / Dairy", "Eggs", "Gluten"];
const avoids = ["Mushrooms", "Coriander", "Onion", "Tomato"];

function Progress({ step }: { step: number }) { return <View style={{ flexDirection: "row", justifyContent: "center", gap: 8 }}>{[0, 1, 2].map((index) => <View key={index} style={{ width: index === step ? 18 : 7, height: 7, borderRadius: 99, backgroundColor: index === step ? colors.primary : colors.border }} />)}</View>; }
function Choice({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} accessibilityRole="button" accessibilityState={{ selected }} style={({ pressed }) => ({ minHeight: 44, justifyContent: "center", paddingHorizontal: 14, borderWidth: 1, borderColor: selected ? colors.primary : colors.border, borderRadius: radius.pill, backgroundColor: selected ? colors.primarySoft : colors.surface, opacity: pressed ? 0.8 : 1 })}><Text style={{ ...typography.metadata, color: selected ? colors.primaryDark : colors.text }}>{label}</Text></Pressable>; }
function PantryVisual() { return <View style={{ gap: spacing.md }}><View style={{ flexDirection: "row", flexWrap: "wrap", justifyContent: "center", gap: 8 }}>{["Tomato", "Egg", "Rice"].map((item) => <View key={item} style={{ paddingHorizontal: 14, paddingVertical: 9, borderRadius: radius.pill, backgroundColor: colors.primarySoft }}><Text style={{ ...typography.metadata, color: colors.primaryDark }}>{item}</Text></View>)}</View><Text style={{ textAlign: "center", color: colors.primary, fontSize: 22 }}>↓</Text><View style={{ borderWidth: 1, borderColor: colors.border, borderRadius: radius.card, padding: spacing.base, backgroundColor: colors.surface, gap: 5 }}><Text style={{ ...typography.cardTitle, color: colors.text }}>Tomato egg rice bowl</Text><Text style={{ ...typography.metadata, color: colors.textSecondary }}>20 min · You have everything</Text></View></View>; }
function MoodVisual() { return <View style={{ gap: spacing.md }}><View style={{ flexDirection: "row", justifyContent: "center", gap: 8 }}><Choice label="Cozy" selected onPress={() => undefined} /><Choice label="20 min" selected={false} onPress={() => undefined} /></View><View style={{ borderWidth: 1, borderColor: colors.border, borderRadius: radius.card, padding: spacing.base, backgroundColor: colors.surface, gap: 5 }}><Text style={{ ...typography.cardTitle, color: colors.text }}>Creamy one-pot pasta</Text><Text style={{ ...typography.metadata, color: colors.textSecondary }}>Quick, comforting, and easy tonight</Text></View></View>; }

export default function Onboarding() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const { userId, isReady } = useSupabaseSession();
  // Onboarding writes only on completion; it must not prefetch private data.
  const profile = useProfile(userId ?? undefined, isReady, false); const preferences = useUserPreferences(userId ?? undefined, false); const device = useDeviceOnboardingCompletion(userId ?? undefined);
  const [step, setStep] = useState(0); const [diet, setDiet] = useState("No preference"); const [selectedGoals, setGoals] = useState<string[]>([]); const [selectedAllergies, setAllergies] = useState<string[]>([]); const [selectedAvoids, setAvoids] = useState<string[]>([]);
  const toggle = (value: string, values: string[], set: (next: string[]) => void) => set(values.includes(value) ? values.filter((item) => item !== value) : [...values, value]);
  const complete = async (savePreferences: boolean) => {
    try {
      if (savePreferences && userId) await preferences.update.mutateAsync({ ...defaultPreferences, dietPreferences: [diet], nutritionGoals: selectedGoals, allergies: selectedAllergies, avoidedIngredients: selectedAvoids.map((value) => ({ type: "custom" as const, value })) });
      if (userId) await profile.completeOnboarding.mutateAsync();
      await device.markCompleted();
      router.replace("/(tabs)");
    } catch { Alert.alert("Couldn’t finish onboarding", "Please check your connection and try again. Your progress has not been completed."); }
  };
  const intro = [
    { title: "Food first.\nDecision second.", body: "Turn ingredients you already have into meals\nyou’ll actually want to cook.", visual: <View style={{ alignItems: "center", justifyContent: "center", minHeight: 190, borderRadius: radius.modal, backgroundColor: colors.primarySoft }}><Text style={{ fontSize: 28, fontWeight: "700", color: colors.primary }}>WhatToCook</Text></View>, cta: "Get started" },
    { title: "Start with what you have.", body: "Add your kitchen ingredients and discover\nrecipes you can make with them.", visual: <PantryVisual />, cta: "Next" },
    { title: "Meals that fit your mood.", body: "Find recipes based on your mood, available\ntime, and food preferences.", visual: <MoodVisual />, cta: "Continue" },
  ];
  const busy = preferences.update.isPending || profile.completeOnboarding.isPending;
  if (step < 3) { const current = intro[step]; return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={{ flexGrow: 1, paddingHorizontal: spacing.lg, paddingTop: insets.top + spacing.lg, paddingBottom: insets.bottom + spacing.lg, backgroundColor: colors.background }}><View style={{ flex: 1, justifyContent: "space-between", gap: spacing.xxl }}><View style={{ alignItems: "flex-end", minHeight: 44 }}><Pressable onPress={() => complete(false)} hitSlop={12}><Text style={{ ...typography.button, color: colors.primary }}>Skip</Text></Pressable></View><View style={{ gap: spacing.xxl }}><View style={{ alignItems: "center", gap: spacing.sm }}><Text style={{ ...typography.cardTitle, color: colors.primary }}>WhatToCook</Text></View>{current.visual}<View style={{ gap: spacing.md }}><Text style={{ ...typography.display, color: colors.text }}>{current.title}</Text><Text style={{ ...typography.body, color: colors.textSecondary }}>{current.body}</Text></View></View><View style={{ gap: spacing.lg }}><Progress step={step} /><PrimaryButton label={current.cta} onPress={() => setStep(step + 1)} />{step > 0 ? <SecondaryButton label="Back" onPress={() => setStep(step - 1)} /> : null}</View></View></ScrollView>; }
  return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={{ flexGrow: 1, paddingHorizontal: spacing.lg, paddingTop: insets.top + spacing.lg, paddingBottom: insets.bottom + spacing.lg, backgroundColor: colors.background }}><View style={{ gap: spacing.lg }}><Pressable onPress={() => setStep(2)} hitSlop={12}><Text style={{ ...typography.button, color: colors.primary }}>‹ Back</Text></Pressable><View style={{ gap: spacing.sm }}><Text style={{ ...typography.display, color: colors.text }}>Make it yours.</Text><Text style={{ ...typography.body, color: colors.textSecondary }}>Tell us what works for you. You can change these preferences anytime.</Text></View><Text style={{ ...typography.cardTitle, color: colors.text }}>Diet</Text><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>{diets.map((item) => <Choice key={item} label={item} selected={diet === item} onPress={() => setDiet(item)} />)}</View><Text style={{ ...typography.cardTitle, color: colors.text }}>Nutrition goals</Text><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>{goals.map((item) => <Choice key={item} label={item} selected={selectedGoals.includes(item)} onPress={() => toggle(item, selectedGoals, setGoals)} />)}</View><Text style={{ ...typography.cardTitle, color: colors.text }}>Allergies</Text><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>{allergies.map((item) => <Choice key={item} label={item} selected={selectedAllergies.includes(item)} onPress={() => toggle(item, selectedAllergies, setAllergies)} />)}</View><Text style={{ ...typography.cardTitle, color: colors.text }}>Avoid ingredients</Text><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>{avoids.map((item) => <Choice key={item} label={item} selected={selectedAvoids.includes(item)} onPress={() => toggle(item, selectedAvoids, setAvoids)} />)}</View><View style={{ flexDirection: "row", alignItems: "flex-start", gap: spacing.sm, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.primarySoft }}><Info size={18} color={colors.primaryDark} style={{ marginTop: 1 }} /><View style={{ flex: 1, gap: 2 }}><Text style={{ ...typography.metadata, color: colors.primaryDark }}>Just the essentials for now</Text><Text style={{ ...typography.caption, color: colors.textSecondary }}>Showing a few popular options to get you started. You can add more preferences anytime in Profile → Food Preferences.</Text></View></View><View style={{ gap: spacing.md, marginTop: spacing.sm }}><PrimaryButton label={busy ? "Saving…" : "Save and continue"} disabled={busy} onPress={() => complete(true)} /><SecondaryButton label="Skip for now" disabled={busy} onPress={() => complete(false)} /></View></View></ScrollView>;
}
