import { ReactNode } from "react";
import { Pressable, StyleSheet, Text, View, ViewStyle } from "react-native";

export const colors = { background: "#FFFFFF", surface: "#F4F4F4", border: "#D9D9D9", textPrimary: "#111111", textSecondary: "#666666", placeholder: "#E5E5E5" };
export function PrimaryButton({ label, onPress, disabled, style }: { label: string; onPress: () => void; disabled?: boolean; style?: ViewStyle }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.primary, disabled && styles.disabled, style]}><Text style={styles.primaryText}>{label}</Text></Pressable>; }
export function SecondaryButton({ label, onPress, disabled, style }: { label: string; onPress: () => void; disabled?: boolean; style?: ViewStyle }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.secondary, disabled && styles.disabled, style]}><Text style={styles.secondaryText}>{label}</Text></Pressable>; }
export function IngredientChip({ label, onPress, removable }: { label: string; onPress?: () => void; removable?: boolean }) { return <Pressable disabled={!onPress} onPress={onPress} style={styles.chip}><Text style={styles.chipText}>{label}{removable ? "  ×" : ""}</Text></Pressable>; }
export function SuggestionChip({ label, selected, onPress }: { label: string; selected?: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.chip, selected && styles.selectedChip]}><Text style={styles.chipText}>{label}</Text></Pressable>; }
export function SectionHeader({ children, action }: { children: ReactNode; action?: ReactNode }) { return <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{children}</Text>{action}</View>; }
export function PlaceholderImage({ height = 112 }: { height?: number }) { return <View style={[styles.placeholder, { height }]}><Text style={styles.placeholderText}>Recipe image</Text></View>; }
export function IngredientRow({ name, status, onRemove }: { name: string; status?: string; onRemove?: () => void }) { return <View style={styles.ingredientRow}><View style={styles.check}><Text>✓</Text></View><View style={{ flex: 1 }}><Text style={styles.rowName}>{name}</Text>{status && <Text style={styles.rowStatus}>{status}</Text>}</View>{onRemove && <Pressable hitSlop={10} onPress={onRemove}><Text style={styles.remove}>Remove</Text></Pressable>}</View>; }
export function CookingProgress({ value }: { value: number }) { return <View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${value}%` }]} /></View>; }
export const styles = StyleSheet.create({
  primary:{minHeight:52,backgroundColor:colors.textPrimary,borderRadius:10,alignItems:"center",justifyContent:"center",paddingHorizontal:16}, primaryText:{color:"white",fontSize:16,fontWeight:"700"}, disabled:{backgroundColor:"#BDBDBD"}, secondary:{minHeight:48,borderWidth:1,borderColor:colors.border,borderRadius:10,alignItems:"center",justifyContent:"center",paddingHorizontal:16}, secondaryText:{color:colors.textPrimary,fontSize:16,fontWeight:"600"}, chip:{borderWidth:1,borderColor:colors.border,borderRadius:20,paddingHorizontal:12,paddingVertical:9,backgroundColor:colors.background}, selectedChip:{backgroundColor:colors.placeholder,borderColor:colors.textPrimary}, chipText:{fontSize:14,color:colors.textPrimary}, sectionHeader:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},sectionTitle:{fontSize:20,fontWeight:"700",color:colors.textPrimary},placeholder:{backgroundColor:colors.placeholder,borderRadius:10,alignItems:"center",justifyContent:"center"},placeholderText:{color:colors.textSecondary,fontSize:13},ingredientRow:{minHeight:56,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:"#EEEEEE"},check:{width:24,height:24,borderRadius:12,backgroundColor:colors.placeholder,alignItems:"center",justifyContent:"center"},rowName:{fontSize:16,fontWeight:"600",color:colors.textPrimary},rowStatus:{fontSize:13,color:colors.textSecondary,marginTop:2},remove:{fontSize:13,color:colors.textSecondary},progressTrack:{height:8,backgroundColor:colors.placeholder,borderRadius:4,overflow:"hidden"},progressFill:{height:"100%",backgroundColor:colors.textPrimary,borderRadius:4}
});
