import { useState } from "react";
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { recipes } from "@/data/mockRecipes";
import { usePantry } from "@/context/PantryContext";
import { colors, IngredientChip, PrimaryButton, SectionHeader, SuggestionChip } from "@/components/ui";
import { RecipeCard } from "@/components/RecipeCard";
const suggestions=["High protein","Quick meal","Healthy","Comfort food","Under 20 min"];
export default function Home(){const router=useRouter();const {pantry}=usePantry();const [query,setQuery]=useState("");return <KeyboardAvoidingView style={styles.page} behavior={Platform.OS==="ios"?"padding":undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.top}><View><Text style={styles.greeting}>Good evening</Text><Text style={styles.heading}>What should we cook?</Text></View><View style={styles.avatar}><Text>◯</Text></View></View><SectionHeader action={<Pressable onPress={()=>router.push("/(tabs)/pantry")}><Text style={styles.link}>View all</Text></Pressable>}>Your Kitchen</SectionHeader><View style={styles.chips}>{pantry.slice(0,5).map((i)=><IngredientChip key={i} label={i}/>)}<Pressable onPress={()=>router.push({ pathname:"/(tabs)/pantry", params:{ add:"1" } })} style={styles.addChip}><Text>+ Add ingredients</Text></Pressable></View><View style={styles.mood}><Text style={styles.label}>What are you in the mood for?</Text><TextInput multiline value={query} onChangeText={setQuery} placeholder="High-protein dinner under 30 minutes" placeholderTextColor={colors.textSecondary} style={styles.input}/><View style={styles.chips}>{suggestions.map((s)=><SuggestionChip key={s} label={s} selected={query===s} onPress={()=>setQuery(s)}/>)}</View></View><PrimaryButton label="Find meals" onPress={()=>router.push("/recipes")}/><SectionHeader>Cook with what I have</SectionHeader><View style={styles.cards}>{recipes.slice(0,2).map((r)=><RecipeCard key={r.id} recipe={r} compact onPress={()=>router.push(`/recipes/${r.id}`)}/>)}</View></ScrollView></KeyboardAvoidingView>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:"white"},content:{padding:20,paddingTop:58,paddingBottom:28,gap:24},top:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},greeting:{fontSize:15,color:colors.textSecondary},heading:{fontSize:28,fontWeight:"700",color:colors.textPrimary,marginTop:4},avatar:{width:40,height:40,borderRadius:20,backgroundColor:colors.placeholder,alignItems:"center",justifyContent:"center"},link:{fontSize:14,fontWeight:"600",color:colors.textPrimary},chips:{flexDirection:"row",flexWrap:"wrap",gap:8},addChip:{paddingHorizontal:12,paddingVertical:9,justifyContent:"center"},mood:{gap:12},label:{fontSize:17,fontWeight:"700",color:colors.textPrimary},input:{minHeight:96,borderWidth:1,borderColor:colors.border,borderRadius:10,padding:12,textAlignVertical:"top",fontSize:16,color:colors.textPrimary},cards:{gap:12}});
