import { useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams } from "expo-router";
import { usePantry } from "@/context/PantryContext";
import { colors, IngredientChip, IngredientRow, PrimaryButton, SectionHeader, SuggestionChip } from "@/components/ui";
import { EmptyState } from "@/components/states";
const suggestions=["Chicken","Eggs","Tomato","Onion","Rice","Paneer","Potato","Capsicum"];
export default function Pantry(){const {pantry,addIngredients,removeIngredient}=usePantry();const {add}=useLocalSearchParams<{add?:string}>();const [visible,setVisible]=useState(add==="1");const [search,setSearch]=useState("");const [selected,setSelected]=useState<string[]>([]);const toggle=(item:string)=>setSelected(old=>old.includes(item)?old.filter(x=>x!==item):[...old,item]);const shown=pantry.filter(item=>item.toLowerCase().includes(search.toLowerCase()));return <View style={styles.page}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Your Pantry</Text><TextInput value={search} onChangeText={setSearch} placeholder="Search ingredients" style={styles.search}/>{pantry.length===0?<EmptyState title="Your pantry is empty" text="Add what you have at home so WhatToCook can suggest better meals." actionLabel="Add ingredients" onAction={()=>setVisible(true)}/>:<><SectionHeader>Available ingredients</SectionHeader>{shown.map(item=><IngredientRow key={item} name={item} status="Available" onRemove={()=>removeIngredient(item)}/>)}<PrimaryButton label="+ Add ingredient" onPress={()=>setVisible(true)}/></>}</ScrollView><Modal visible={visible} transparent animationType="slide" onRequestClose={()=>setVisible(false)}><View style={styles.overlay}><Pressable style={StyleSheet.absoluteFill} onPress={()=>setVisible(false)}/><View style={styles.sheet}><Text style={styles.sheetTitle}>Add Ingredients</Text><Text style={styles.support}>Choose ingredients you have at home.</Text><View style={styles.chips}>{suggestions.map(item=><SuggestionChip key={item} label={item} selected={selected.includes(item)} onPress={()=>toggle(item)}/>)}</View>{selected.length>0&&<View style={styles.chips}>{selected.map(item=><IngredientChip key={item} label={item} removable onPress={()=>toggle(item)}/>)}</View>}<PrimaryButton label={`Add ${selected.length || ""} ingredient${selected.length===1?"":"s"}`} disabled={!selected.length} onPress={()=>{addIngredients(selected);setSelected([]);setVisible(false)}}/></View></View></Modal></View>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:"white"},content:{padding:20,paddingTop:58,paddingBottom:32,gap:16},title:{fontSize:28,fontWeight:"700"},search:{height:50,borderWidth:1,borderColor:colors.border,borderRadius:10,paddingHorizontal:12,fontSize:16},overlay:{flex:1,justifyContent:"flex-end",backgroundColor:"rgba(0,0,0,.25)"},sheet:{backgroundColor:"white",borderTopLeftRadius:20,borderTopRightRadius:20,padding:20,gap:14},sheetTitle:{fontSize:22,fontWeight:"700"},support:{color:colors.textSecondary},chips:{flexDirection:"row",flexWrap:"wrap",gap:8}});
