import { useMemo, useState } from "react";
import { Alert, KeyboardAvoidingView, Modal, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { useRouter } from "expo-router";
import { colors, PrimaryButton, SecondaryButton, SectionHeader, SuggestionChip } from "@/components/ui";
import { AvoidedIngredient, useApp } from "@/context/AppContext";
import { getIngredientById, ingredients } from "@/data/ingredients";
import { searchIngredients } from "@/domain/ingredients/ingredient-search";

const diets=["No preference","Vegetarian","Vegan","Eggetarian","Pescatarian","Jain","Halal","Kosher"];
const goals=["High protein","Low calorie","High fiber","Low carb","Balanced","Heart healthy","Low sodium","Low sugar","Weight management","Muscle gain","Quick meals","Budget friendly"];
const allergies=["Peanuts","Tree nuts","Milk / Dairy","Eggs","Wheat","Gluten","Soy","Fish","Shellfish","Sesame","Mustard","Celery"];
type Sheet="diet"|"goals"|"allergies"|"avoid"|null;
const norm=(v:string)=>v.trim().toLocaleLowerCase("en-US");
const summary=(items:string[],empty="None")=>!items.length?empty:items.length>2?`${items.slice(0,2).join(", ")} +${items.length-2}`:items.join(", ");

export default function Profile(){
  const router=useRouter(); const {isAuthenticated,user,preferences,updatePreferences}=useApp();
  const [sheet,setSheet]=useState<Sheet>(null),[diet,setDiet]=useState(preferences.diet),[draft,setDraft]=useState<string[]>([]),[avoid,setAvoid]=useState<AvoidedIngredient[]>([]),[search,setSearch]=useState(""),[custom,setCustom]=useState(""),[customOpen,setCustomOpen]=useState(false);
  const open=(kind:Exclude<Sheet,null>)=>{setSheet(kind);setSearch("");setCustom("");setCustomOpen(false);setDiet(preferences.diet);setDraft(kind==="goals"?preferences.nutritionGoals:kind==="allergies"?preferences.allergies:[]);setAvoid(kind==="avoid"?preferences.avoidedIngredients:[])};
  const toggle=(value:string)=>setDraft(old=>old.some(x=>norm(x)===norm(value))?old.filter(x=>norm(x)!==norm(value)):[...old,value]);
  const ingredientResults=useMemo(()=>searchIngredients(search,ingredients),[search]);
  const options=useMemo(()=>(sheet==="goals"?goals:allergies).filter(item=>norm(item).includes(norm(search))),[sheet,search]);
  const avoidLabel=(item:AvoidedIngredient)=>item.type==="canonical"?getIngredientById(item.ingredientId)?.name??item.ingredientId:item.value;
  const addAvoid=(id:string)=>setAvoid(old=>old.some(item=>item.type==="canonical"&&item.ingredientId===id)?old.filter(item=>item.type!=="canonical"||item.ingredientId!==id):[...old,{type:"canonical",ingredientId:id}]);
  const addCustom=()=>{const value=custom.trim();if(!value)return;if(sheet==="diet")setDiet(value);else if(sheet==="avoid"){const exact=searchIngredients(value,ingredients).find(r=>norm(r.ingredient.name)===norm(value)||r.ingredient.aliases.some(a=>norm(a)===norm(value)))?.ingredient;if(!avoid.some(item=>norm(avoidLabel(item))===norm(value)))setAvoid(old=>[...old,exact?{type:"canonical",ingredientId:exact.id}:{type:"custom",value}]);}else setDraft(old=>old.some(item=>norm(item)===norm(value))?old:[...old,value]);setCustom("");setCustomOpen(false)};
  const save=()=>{if(sheet==="diet")updatePreferences({diet:diet.trim()||"No preference"});if(sheet==="goals")updatePreferences({nutritionGoals:draft});if(sheet==="allergies")updatePreferences({allergies:draft});if(sheet==="avoid")updatePreferences({avoidedIngredients:avoid});setSheet(null)};
  const avoidLabels=preferences.avoidedIngredients.map(avoidLabel);
  const title=sheet==="diet"?"Diet":sheet==="goals"?"Nutrition goals":sheet==="allergies"?"Allergies":"Avoid ingredients";
  const support=sheet==="diet"?"Choose the option that best matches how you usually eat.":sheet==="goals"?"Choose what matters most when recommending meals.":sheet==="allergies"?"Select foods you are allergic to so we can avoid recommending recipes that contain them.":"Add ingredients you don't want included in recipe recommendations.";
  const selected=sheet==="avoid"?avoid.map(item=>({key:item.type==="canonical"?item.ingredientId:`custom-${item.value}`,label:avoidLabel(item),remove:()=>setAvoid(old=>old.filter(entry=>entry!==item))})):draft.map(item=>({key:item,label:item,remove:()=>toggle(item)}));
  return <View style={styles.page}>
    <ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Profile</Text><View style={styles.profile}><View style={styles.avatar}><Text>◯</Text></View><View><Text style={styles.name}>{isAuthenticated?user?.name:"Guest"}</Text><Text style={styles.muted}>{isAuthenticated?user?.email:"Personalize your cooking experience"}</Text></View></View><SectionHeader>Food Preferences</SectionHeader><SettingsRow label="Diet" value={preferences.diet||"No preference"} onPress={()=>open("diet")}/><SettingsRow label="Nutrition goals" value={summary(preferences.nutritionGoals)} onPress={()=>open("goals")}/><SettingsRow label="Allergies" value={summary(preferences.allergies)} onPress={()=>open("allergies")}/><SettingsRow label="Avoid ingredients" value={summary(avoidLabels)} onPress={()=>open("avoid")}/><SectionHeader>App Settings</SectionHeader><SettingsRow label="Units" value={preferences.units} onPress={()=>updatePreferences({units:preferences.units==="Metric"?"Imperial":"Metric"})}/><View style={styles.setting}><View><Text style={styles.label}>Notifications</Text><Text style={styles.value}>{preferences.notificationsEnabled?"On":"Off"}</Text></View><Switch value={preferences.notificationsEnabled} onValueChange={value=>updatePreferences({notificationsEnabled:value})}/></View><SettingsRow label="Appearance" value={preferences.appearance} onPress={()=>Alert.alert("Appearance","This screen will be added later.")}/><SectionHeader>Account</SectionHeader>{isAuthenticated?<SettingsRow label="Account details" onPress={()=>router.push("/account")}/>:<SettingsRow label="Sign in" onPress={()=>router.push("/auth/sign-in")}/>}</ScrollView>
    <Modal visible={sheet!==null} transparent animationType="slide" onRequestClose={()=>setSheet(null)}><KeyboardAvoidingView behavior="padding" style={styles.overlay}><Pressable style={StyleSheet.absoluteFill} onPress={()=>setSheet(null)}/><ScrollView contentContainerStyle={styles.sheet} keyboardShouldPersistTaps="handled"><Text style={styles.sheetTitle}>{title}</Text><Text style={styles.support}>{support}</Text>{sheet==="allergies"&&<Text style={styles.note}>WhatToCook should not be relied on as the only source for allergy safety. Always check ingredient labels and recipe details.</Text>}{sheet!=="diet"&&<TextInput value={search} onChangeText={setSearch} placeholder={sheet==="avoid"?"Search ingredients":sheet==="allergies"?"Search allergies":"Search goals"} style={styles.input}/>}{sheet==="diet"?<View style={styles.options}>{diets.map(option=><Pressable key={option} style={styles.optionRow} onPress={()=>setDiet(option)}><Text style={styles.optionText}>{option}</Text><Text>{diet===option?"●":"○"}</Text></Pressable>)}</View>:<><Text style={styles.selectedTitle}>Selected{sheet==="allergies"?" allergies":""}</Text><View style={styles.chips}>{selected.map(item=><SuggestionChip key={item.key} label={`${item.label} ×`} onPress={item.remove}/>)}</View>{!selected.length&&<Text style={styles.empty}>Nothing selected yet</Text>}{sheet==="allergies"&&<SuggestionChip label="None" selected={!draft.length} onPress={()=>setDraft([])}/>}<View style={styles.options}>{(sheet==="avoid"?ingredientResults.map(result=>({key:result.ingredient.id,label:result.ingredient.name,selected:avoid.some(item=>item.type==="canonical"&&item.ingredientId===result.ingredient.id),onPress:()=>addAvoid(result.ingredient.id)})):options.map(option=>({key:option,label:option,selected:draft.some(item=>norm(item)===norm(option)),onPress:()=>toggle(option)}))).map(option=><SuggestionChip key={option.key} label={option.label} selected={option.selected} onPress={option.onPress}/>)}</View>{search&&!(sheet==="avoid"?ingredientResults.length:options.length)&&<Text style={styles.empty}>No matching options</Text>}</>}{customOpen?<View style={styles.custom}><TextInput value={custom} onChangeText={setCustom} placeholder={sheet==="diet"?"e.g. Flexitarian":sheet==="avoid"?"e.g. Black garlic sauce":sheet==="allergies"?"e.g. Kiwi":"e.g. Iron rich"} style={styles.input}/><View style={styles.actions}><SecondaryButton label="Cancel" onPress={()=>{setCustom("");setCustomOpen(false)}} style={{flex:1}}/><PrimaryButton label="Add" onPress={addCustom} style={{flex:1}}/></View></View>:<Pressable onPress={()=>setCustomOpen(true)}><Text style={styles.customLink}>{sheet==="diet"?"Other":sheet==="avoid"?"Can't find the ingredient? + Add custom ingredient":"Can't find it? + Add custom"}</Text></Pressable>}<PrimaryButton label={sheet==="diet"?"Save":sheet==="goals"?"Save goals":sheet==="allergies"?"Save allergies":"Save ingredients"} onPress={save}/></ScrollView></KeyboardAvoidingView></Modal>
  </View>;
}
function SettingsRow({label,value,onPress}:{label:string;value?:string;onPress:()=>void}){return <Pressable onPress={onPress} style={styles.setting}><View><Text style={styles.label}>{label}</Text>{value&&<Text style={styles.value}>{value}</Text>}</View><Text style={styles.chevron}>›</Text></Pressable>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:"white"},content:{padding:20,paddingTop:58,paddingBottom:32,gap:10},title:{fontSize:28,fontWeight:"700"},profile:{flexDirection:"row",alignItems:"center",gap:12,backgroundColor:colors.surface,borderRadius:12,padding:16,marginBottom:8},avatar:{width:44,height:44,borderRadius:22,backgroundColor:colors.placeholder,alignItems:"center",justifyContent:"center"},name:{fontSize:17,fontWeight:"700"},muted:{fontSize:14,color:colors.textSecondary,marginTop:3},setting:{minHeight:58,borderBottomWidth:1,borderColor:"#eee",flexDirection:"row",justifyContent:"space-between",alignItems:"center"},label:{fontSize:16,fontWeight:"600"},value:{fontSize:13,color:colors.textSecondary,marginTop:3},chevron:{fontSize:24,color:colors.textSecondary},overlay:{flex:1,justifyContent:"flex-end",backgroundColor:"rgba(0,0,0,.25)"},sheet:{backgroundColor:"white",borderTopLeftRadius:20,borderTopRightRadius:20,padding:20,gap:14,maxHeight:"90%"},sheetTitle:{fontSize:22,fontWeight:"700"},support:{color:colors.textSecondary,lineHeight:20},note:{fontSize:12,color:colors.textSecondary,lineHeight:18,backgroundColor:colors.surface,padding:10,borderRadius:8},input:{height:50,borderWidth:1,borderColor:colors.border,borderRadius:10,paddingHorizontal:12},selectedTitle:{fontWeight:"700"},chips:{flexDirection:"row",flexWrap:"wrap",gap:8},options:{flexDirection:"row",flexWrap:"wrap",gap:8},optionRow:{width:"100%",minHeight:46,borderBottomWidth:1,borderColor:colors.border,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},optionText:{fontSize:16},empty:{color:colors.textSecondary,fontSize:14},customLink:{fontWeight:"600",paddingVertical:4},custom:{gap:8},actions:{flexDirection:"row",gap:8}});
